name: bayes_pta
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.12.2

  # Core scientific computing
  - numpy=1.26.4
  - scipy=1.11.4
  - pandas=2.1.4
  - scikit-learn=1.3.0

  # Visualization
  - matplotlib=3.8.3
  - seaborn=0.12.2

  # Jupyter and development
  - ipykernel=6.29.3
  - ipython=8.22.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1

  # Data processing
  - bottleneck=1.3.7
  - numexpr=2.8.7
  - joblib=1.2.0

  # Utilities
  - tqdm
  - psutil=5.9.8
  - packaging=23.2

  # Testing and debugging
  - debugpy=1.8.1

  # Build tools
  - pip=24.0
  - setuptools=69.1.1
  - wheel=0.42.0

  # Pip dependencies (for packages not available in conda)
  - pip:
      - playwright>=1.51.0
      - pyee>=12.1.1
      - greenlet>=3.2.1
      # Add your local package in editable mode after environment creation
      # - -e .